# Default values for alerts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: scmmanager/alerts
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: alerts.scm-manager.org
      paths:
        - /api

  tls:
    - secretName: alerts-tls-secret
      hosts:
        - alerts.scm-manager.org

resources:
  limits:
    memory: 30Mi
  requests:
    cpu: 100m
    memory: 30Mi

nodeSelector: {}

tolerations: []

affinity: {}
